<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" media="screen" href="http://tarruda.github.com/bootstrap-datetimepicker/assets/css/bootstrap-datetimepicker.min.css"/>
<link media="screen" rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/css/bootstrap.min.css"/>
<link media="screen" rel="stylesheet" href="http://dw.socialgamenet.com//static/css/main.css"/>
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript" src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"></script>
<script type="text/javascript" src="http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.pt-BR.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.6.0/ui-bootstrap-tpls.min.js" type="text/javascript"></script>
<script src="http://code.highcharts.com/stock/highstock.src.js" type="text/javascript"></script>
<script src="http://dw.socialgamenet.com//static/js/app.js" type="text/javascript"></script>
<script src='http://dw.socialgamenet.com//static/js/services.js' type="text/javascript"></script>
<script src="http://dw.socialgamenet.com//static/js/controllers.js" type="text/javascript"></script>
<script src="http://dw.socialgamenet.com//static/js/directives.js" type='text/javascript'></script>
<title>ApiDoc - generated by automan</title>
</head>

<body ng-app="ApiExplorerModule">
<header class="navbar navbar-inverse" role="banner">
    <div class="navbar-inner">
        <a class="brand navbar-brand" href="/" style="font-size: 24px;">FunPlus</a>
    </div>
    <ul class="nav navbar-nav pull-right hidden-xs">
    </ul>
</header>

<div ng-controller="ApiExplorerController">
    <div class="conent">
    <div class="well"><h3><?=$parsedResult['filename']?></h3></div>
<?php
foreach($parsedResult['api'] as $api) {
    echo '<div class="row">';
    echo "<p>", $api['action'], "</p>";
    echo json_encode($api['io']['input'], JSON_PRETTY_PRINT), "<br/>";
    echo json_encode($api['io']['output'], JSON_PRETTY_PRINT);
    echo '</div>';
}

?>
    </div>
    <hr>
</div>
</body>
</html>
