#!/usr/bin/env python
#encoding=utf-8
'''Prerequirement:
sudo easy_install confluence '''

import sys
import os
import json
from confluence import Confluence

URL='http://wiki.ifunplus.cn/'
USER=os.getenv('WIKI_USER')
PASS=os.getenv('WIKI_PASSWD')
SPACE=os.getenv('SPACE')

def load_config(cf='config.json'):
    global URL, SPACE, USER, PASS
    with open(cf) as f:
        config = json.load(f)
        URL = config['wiki']['url']
        if not SPACE:
            SPACE = config['wiki']['space']
        if not USER:
            USER = config['wiki']['username']
        if not PASS:
            PASS = config['wiki']['password']

def load_const(fn='output/automan.const'):
    with open(fn) as f:
        const = json.load(f)
        return '{code:JavaScript}' + json.dumps(const, indent=4) + '{code}'

def wikitag(line):
    js = json.loads(line)
    return '{code:JavaScript}' + json.dumps(js, indent=4) + '{code}'

def wiki_content(fn):
    ''' -> title, content'''
    n = 0
    title, content = '', ''
    for line in open(fn):
        if n == 0:
            # title
            content += line
            if title == '':
                title = line.split(':')[0] + 'Service'
        elif n == 1:
            # input json
            content += 'Request:\n'
            content += wikitag(line) + '\n'
        elif n == 2:
            # ouptut json
            content += 'Response:\n'
            content += wikitag(line) + '\n'
        n += 1
        n %= 3

    return title, content

def main(apifile):
    load_config(os.path.abspath(os.path.dirname(__file__)) + '/config.json')
    cf = Confluence(url=URL, username=USER, password=PASS)
    pageTitle, pageContent = wiki_content(apifile)
    fullContent = 'The following content is genereated by automan\n\n'
    fullContent += 'const\n' + load_const() + '\n'
    fullContent += pageContent
    ok = cf.storePageContent(pageTitle, SPACE, fullContent)
    if ok:
        print 'feed wiki[%s] ok' % pageTitle
    else:
        print 'feed wiki[%s] fail' % pageTitle

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print 'Usage: %s api_filename' % sys.argv[0]
        sys.exit(0)

    main(sys.argv[1])
