#!/usr/bin/php
<?php

require_once 'bootstrap.php';

/**
 * Automatically generate api doc according our customized phpdoc tags.
 *
 * Currently supported tags:
 * InputTag
 * OutputTag
 */
class Automan
{
    const SERVICE = 'Services\\';
    const HTTP_HOST = 'http://localhost';
    const VERBOSE = FALSE;

    private function _baseClassName($filename)
    {
        return substr(basename($filename), 0, -strlen('.php'));
    }

    private function _fullQualifiedClassName($filename)
    {
        return self::SERVICE . $this->_baseClassName($filename);
    }

    private function _handleAnnotationTag($filename, Annotation $tag)
    {
        if ($tag instanceof InputTag) {
            return $this->_handleInputTag($filename, $tag);
        } elseif ($tag instanceof OutputTag) {
            return $this->_handleOutputTag($filename, $tag);
        }
    }

    private function _handleInputTag($filename, InputTag $tag)
    {
        return array(
            'input' => $tag->getJsonArray($filename),
        );

    }

    private function _handleOutputTag($filename, OutputTag $tag)
    {
        return array(
            'output' => $tag->getJsonArray($filename),
        );
    }

    private function _getApiUrl($filename, ReflectionMethod $method)
    {
        return self::HTTP_HOST . '/api/?class=' . $this->_baseClassName($filename)
            . '&method=' . $method->name
            . '&params=';
    }

    public function parsePhpFile($filename)
    {
        require_once $filename;

        $clsname = $this->_fullQualifiedClassName($filename);
        if (self::VERBOSE) {
            echo "Parsing class $clsname..." . PHP_EOL;
        }

        $ret = array(
            'filename' => $filename,
        );
        $reflection = new ReflectionClass($clsname);
        // parse each method of the controller class
        foreach ($reflection->getMethods() as $method) {
            // handle this controller action
            $p = new ReflectionAnnotatedMethod($method->class, $method->name);
            $hasTag = FALSE;
            $docs = array();
            foreach (array('InputTag', 'OutputTag') as $tagName) {
                $tag = $p->getAnnotation($tagName);
                if (!$tag) {
                    continue;
                }

                $hasTag = TRUE;
                if ($res = $this->_handleAnnotationTag($filename, $tag)) {
                    foreach ($res as $key => $val) {
                        $docs[$key] = $val;
                    }
                }
            }

            if ($hasTag) {
                $ret['api'][] = array(
                    'controller' => $this->_baseClassName($filename),
                    'action' => $method->name,
                    'url' => $this->_getApiUrl($filename, $method),
                    'io' => $docs,
                );
            }
        }

        return $ret;
    }

    public function generateTestScript($parsedResult)
    {

    }

    public function generateApiDoc($parsedResult)
    {

    }

}

function showHelp() {
    global $argv;
    echo "Usage: " . $argv[0] . " filename [filename]\n";
}

function main() {
    global $argv;
    ini_set('register_argc_argv', 'On');
    if (count($argv) == 1) {
        showHelp();
        exit(0);
    }

    $man = new Automan();
    foreach ($argv as $idx => $filename) {
        if ($idx == 0) {
            continue;
        }

        $result = $man->parsePhpFile($filename);
        $man->generateTestScript($result);
        $man->generateApiDoc($result);
    }
}

main();
