#!/usr/bin/env python
#encoding=utf-8
'''Prerequirement:
sudo easy_install confluence '''

import sys
import json
from confluence import Confluence

URL='http://wiki.localhost.cn/'
USER='peng.gao'
PASS='peng.gao'
SPACE='DG'

def wikitag(line):
    js = json.loads(line)
    return '{code:JavaScript}' + json.dumps(js, indent=4) + '{code}'

def wiki_content(fn):
    ''' -> title, content'''
    n = 0
    title = ''
    content = 'The following content is genereated by automan\n\n'
    for line in open(fn):
        if n == 0:
            # title
            content += line
            if title == '':
                title = line.split(':')[0] + 'Service'
        elif n == 1:
            # input json
            content += 'Request:\n'
            content += wikitag(line) + '\n'
        elif n == 2:
            # ouptut json
            content += 'Response:\n'
            content += wikitag(line) + '\n'
        n += 1
        n %= 3

    return title, content

def main():
    cf = Confluence(url=URL, username=USER, password=PASS)
    pageTitle, pageContent = wiki_content(sys.argv[1])
    ok = cf.storePageContent(pageTitle, SPACE, pageContent)
    if ok:
        print 'feed wiki[%s] ok' % pageTitle
    else:
        print 'feed wiki[%s] fail' % pageTitle

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print 'Usage: %s api_filename' % sys.argv[0]
        sys.exit(0)

    main()
